name: Coverage Tests
on:
  workflow_run:
    workflows: [ "PyTest" ]
    branches:
      - '**'
    types:
      - completed

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Python Cov
        uses: orgoro/coverage@v2
        with:
          coverageFile: ./coverage/coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}